/* AUTO GENERATED BY make. DO NOT EDIT! */

#define RELEASE ""
#define BLAME "LibXenon.org"
#define DATE "2019-08-30"
#define GITREV ""

#define VERSION RELEASE "-git-" GITREV
#define LONGVERSION "(" BLAME ")"
